ALTER TABLE endpoints ADD COLUMN IF NOT EXISTS secret TEXT NOT NULL DEFAULT '';
ALTER TABLE endpoints ADD COLUMN IF NOT EXISTS slack_webhook_url TEXT NOT NULL DEFAULT '';
ALTER TABLE endpoints ADD COLUMN IF NOT EXISTS rate_limit_per_second INT NOT NULL DEFAULT 10;
ALTER TABLE endpoints ADD COLUMN IF NOT EXISTS rate_limit_burst INT NOT NULL DEFAULT 20;
