apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hookforge.fullname" . }}-secret
  labels:
    {{- include "hookforge.labels" . | nindent 4 }}
type: Opaque
stringData:
  SIGNING_SECRET: "{{ .Values.config.signingSecret }}"
  SMTP_PASSWORD: "{{ .Values.config.smtpPassword }}"
  ADMIN_API_KEY: "{{ .Values.config.adminApiKey }}"
